# Generated by Django 4.2.16 on 2024-09-27 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gratitude', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gratitudeentry',
            options={'verbose_name_plural': 'Gratitude Entries'},
        ),
    ]
